version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "03:00"
      timezone: "Asia/Tokyo"
    labels: ["dependencies", "deps-actions"]
    open-pull-requests-limit: 5
    groups:
      actions:
        patterns: ["*"]

  - package-ecosystem: "npm"
    directory: "/mock/v1/web"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "03:10"
      timezone: "Asia/Tokyo"
    labels: ["dependencies", "deps-node", "area-web"]
    open-pull-requests-limit: 5
    groups:
      web-deps:
        patterns: ["*"]
