version: '3'

services:
  node-app:
    build:
      context: ..
      dockerfile: ./.devcontainer/Dockerfile
    image: agile-pmbok-assist-dev:node24
    command: sleep infinity
    volumes:
      - ..:/workspaces/agile-pmbok-assist
